### ISSUE TITLE
t (lowercase T, the 20th letter in the english alphabet) and + (plus sign) appear identical?

### ISSUE THREAD

**Issue by george-tsiros** [weirdoonthebus/Kepler-452b#3]
It would be so, so helpful if they were adjusted even a tiny tiny bit?
maybe make `t` like this:

![image](https://user-images.githubusercontent.com/54522275/188267289-1ecdc9a5-4898-4bcf-953b-3479a3f98c85.png)

I made it look so ugly :( I am sorry

thank you wholeheartedly for the font, it is gorgeous

**Comment by weirdoonthebus** [comment]
Thank you very much for your suggestion. This change has been added in the latest push.
